### ISSUE TITLE
Postgres 9.5 required

### ISSUE THREAD

**Issue by h1z1** [simon987/yt-metadata#2]
More a warning to anyone else who may have run into this.  The error certainly is not obvious.

```
$ python36 ../import.py 
/fas250/.local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Created license 'Creative Commons Attribution license (reuse allowed)' with id 2
Traceback (most recent call last):
  File "../import.py", line 252, in <module>
    import_recursive("/dev/shm/yt")
  File "../import.py", line 248, in import_recursive
    import_json(filename)
  File "../import.py", line 171, in import_json
    create_uploader(cursor, meta["uploader"], meta["uploader_id"], meta["uploader_url"])
  File "../import.py", line 61, in create_uploader
    (ul_id, url, name))
psycopg2.ProgrammingError: syntax error at or near "ON"
LINE 1: ...ttp://www.youtube.com/user/foo','foo user') ON CONFLIC...
                                                             ^

```

Though some distros may have newer versions, not all do.  CentOS shipps with 9.2

**Comment by simon987** [comment]
I will leave a note in the readme, thank you!
